Repository KoheiB/cipher_application, pull requests merged in 2021-01, with the labels that each got.

#13 add scraping data, cord
  etc/2020-12-31_cipher_data.csv
  etc/get_card_data.py
  etc/get_card_images.py
Labels: function, research

#15 #14 add draggable
  .eslintrc.js
  components/Card.vue
  components/PickedCard.vue
  package-lock.json
  package.json
  pages/buildDeck.vue
Labels: appearance, function

#19 #4 create header
  assets/sass/variables.scss
  assets/variables.scss
  components/BottomNav.vue
  components/BottomNavSample.vue
  components/Header.vue
  components/HeaderSample.vue
  layouts/default.vue
  nuxt.config.js
Labels: appearance

#29 #27_modify data model about multiple coloums.
  etc/import_data.js
  store/data.md
Labels: database, fix

#30 #28_add unitNames, fix Cards data
  etc/2021-01-24_cipher_data.csv
  etc/get_card_data.py
  etc/import_data.js
  etc/outputUnitNames.js
  etc/unitNames.txt
  mixins/UnitNames.js
Labels: database, fix

#31 #24 fix header and bottumNavi
  components/BottomNav.vue
  components/Header.vue
  components/PickedCard.vue
Labels: fix

#22 #21 plugin
  .gitignore
  nuxt.config.js
  package-lock.json
  package.json
  plugins/auth.js
  plugins/firebase.js
  plugins/infiniteloading.js
  storage.rules
Labels: function

#33 #32 unit name filter items
  etc/outputUnitNames.js
  etc/unitNames.txt
  mixins/UnitNameFilterItems.js
  mixins/UnitNames.js
Labels: fix
