Repository KoheiB/cipher_application, pull requests merged in 2021-02, with the labels that each got.

#25 #23 search card list
  components/Header.vue
  mixins/UnitNameFilterItems.js
  pages/buildDeck.vue
Labels: appearance, function

#35 #34 デッキ作成画面　デッキビュー　基礎部分
  components/BottomNav.vue
  components/PickedCard.vue
  components/PickedCardList.vue
  mixins/UnitNameFilterItems.js
  pages/buildDeck.vue
Labels: appearance, function

#50 FIX:データモデル修正、UnitNameFilterItems修正、Firestoreへのデータインポート機能を微修正
  etc/import_data.js
  etc/unitNames.txt
  etc/unitNamesFilterItems.xls
  mixins/UnitNameFilterItems.js
  pages/buildDeck.vue
  store/data.md
Labels: database, fix

#51 ADD:yarn.lock
  yarn.lock
Labels: function

#49 #42 add mixins
  components/UseCards.vue
  components/UseCardsObj.vue
  constant/constant.js
  nuxt.config.js
  pages/buildDeck.vue
  plugins/global.js
Labels: fix, function, refactor

#56 #55 readme
  README.md
Labels: design, enhancement

#53 FIX: infinite-loading不具合修正
  pages/buildDeck.vue
Labels: fix, function
